[package]
name = "leptos_reactive"
version = "0.0.8"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Reactive system for the Leptos web framework."

[dependencies]
log = "0.4"
slotmap = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
futures = { version = "0.3" }
js-sys = { version = "0.3", optional = true }
serde-wasm-bindgen = { version = "0.4", optional = true }
serde_json = { version = "1", optional = true }
base64 = { version = "0.13", optional = true }
thiserror = "1"
tokio = { version = "1", features = ["rt"], optional = true }
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
web-sys = { version = "0.3", optional = true, features = ["Element"] }

[dev-dependencies]
sycamore = "0.8.0-beta.7"
tokio-test = "0.4"

[features]
default = ["resource"]
csr = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:web-sys"]
hydrate = ["dep:base64", "dep:js-sys", "dep:serde-wasm-bindgen", "dep:serde_json", "dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:web-sys"]
ssr = ["dep:base64", "dep:serde_json", "dep:tokio"]
resource = []
transition = []